services:
  # Base de datos PostgreSQL local
  postgres-db:
    image: postgres:15-alpine
    container_name: caseroya-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_password_local
      POSTGRES_DB: caseroya_db
    ports:
      - "5432:5432"
    volumes:
      - caseroya_data:/var/lib/postgresql/data

volumes:
  caseroya_data:
